#!/bin/bash
found=$(git branch | sed 's/[\*]//g')
found=($found)

red='\033[0;31m'
yellow='\033[1;33m'
nc='\033[0m' # No Color

del='-d'
if [ "$1" == '-D' ];then
   del='-D'
fi

for i in "${!found[@]}"
do
  if [ "${found[$i]}" != "master" ] && [ "${found[$i]}" != "develop" ];then
    echo -n -e "${yellow}branch ${del}${red} to delete branch ${yellow}${found[$i]}${red}? ${nc}"
    read -r response
    if [ "$response" == "y" ] || [ "$response" == "yes" ];then
       git branch "${del}" "${found[$i]}"
    elif [ "$response" == "q" ] || [ "$response" == "quit" ];then
        exit 1
    else
        echo "Skipped ${found[$i]}."
    fi
  fi
done
