#!/bin/bash
((!$#)) && echo No branch name, command ignored! && exit 1
found=$(git branch | grep "$1" | sed 's/[\*]//g')
found=($found)

# No items were found. Exit.
if [ ${#found[*]} == 0 ];then
  echo "No matches found for " "$1"
  exit 0
fi

# If there is only one result, check it out directly
if [ ${#found[*]} == 1 ];then
  git checkout "${found[0]}"
  exit 0
fi

# List results and allow user to select one.
echo "Found the following..."
for i in "${!found[@]}"
do
  echo "$i": "${found[$i]}"
done

echo -n "Which branch should I checkout? [quit] "
read -r id

# If the input is integer and maps to an array key,
# checkout the repo.
if [ "$id" -eq "$id" ] 2> /dev/null && [ "${found[id]}" ]
then
  git checkout "${found[id]}"
fi

exit 0