#!/bin/bash
found=$(git branch | sed 's/[\*]//g')
found=($found)

red='\033[0;31m'
yellow='\033[1;33m'
nc='\033[0m' # No Color

for i in "${!found[@]}"
do
  if [ "${found[$i]}" != "master" ] && [ "${found[$i]}" != "develop" ];then
    echo -n -e "${yellow}branch -d${red} to delete branch ${yellow}${found[$i]}${red}? ${nc}"
    read -r response
    if [ "$response" == "y" ] || [ "$response" == "yes" ];then
       git branch -d "${found[$i]}"
    else
        echo "Skipped ${found[$i]}."
    fi
  fi
done
